# Generated by Django 5.2.14 on 2026-05-17 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("credits", models.PositiveIntegerField()),
                (
                    "bonus_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Extra credits included in this pack"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "credit_packs",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plans_section_title",
                    models.CharField(default="Subscription plans", max_length=200),
                ),
                (
                    "plans_section_description",
                    models.TextField(
                        blank=True,
                        default="Choose monthly or yearly billing. Yearly plans include included credits each month.",
                    ),
                ),
                (
                    "monthly_toggle_label",
                    models.CharField(default="Monthly", max_length=64),
                ),
                (
                    "monthly_description",
                    models.TextField(
                        blank=True,
                        default="Pay month-to-month. Cancel anytime. Credits refresh each billing period.",
                    ),
                ),
                (
                    "yearly_toggle_label",
                    models.CharField(default="Yearly", max_length=64),
                ),
                (
                    "yearly_description",
                    models.TextField(
                        blank=True,
                        default="One payment per year — best value for studios with steady output.",
                    ),
                ),
                (
                    "yearly_discount_note",
                    models.CharField(
                        blank=True, default="Save ~17% vs monthly", max_length=120
                    ),
                ),
                (
                    "credits_section_title",
                    models.CharField(default="Buy credits", max_length=200),
                ),
                (
                    "credits_section_description",
                    models.TextField(
                        blank=True,
                        default="Top up anytime. Purchased credits never expire and stack with your plan allowance.",
                    ),
                ),
                (
                    "credits_footer_note",
                    models.TextField(
                        blank=True,
                        default="Credits are consumed per render based on the model selected in the editor.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pricing settings",
                "verbose_name_plural": "pricing settings",
                "db_table": "pricing_settings",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="monthly_description",
            field=models.TextField(
                blank=True,
                help_text="Shown on pricing when Monthly billing is selected",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="yearly_description",
            field=models.TextField(
                blank=True, help_text="Shown on pricing when Yearly billing is selected"
            ),
        ),
    ]
