"""django-jazzmin admin theme for Flowframe."""

JAZZMIN_SETTINGS = {
    "site_title": "Flowframe Admin",
    "site_header": "Flowframe",
    "site_brand": "Flowframe",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Flowframe yönetim paneline hoş geldiniz",
    "copyright": "Flowframe",
    "search_model": [
        "auth_system.User",
        "catalog.AIModel",
        "catalog.AIProvider",
        "catalog.CapabilityCategory",
    ],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Site", "url": "/", "new_window": True},
        {
            "name": "AI Providers",
            "url": "admin:catalog_aiprovider_changelist",
            "permissions": ["catalog.view_aiprovider"],
        },
        {
            "name": "AI Models",
            "url": "admin:catalog_aimodel_changelist",
            "permissions": ["catalog.view_aimodel"],
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "catalog",
        "auth_system",
        "rendering",
        "billing",
        "projects",
        "workflow",
        "assets",
    ],
    "custom_links": {
        "catalog": [
            {
                "name": "AI Providers (servisler)",
                "url": "admin:catalog_aiprovider_changelist",
                "icon": "fas fa-plug",
                "permissions": ["catalog.view_aiprovider"],
            },
            {
                "name": "AI Models",
                "url": "admin:catalog_aimodel_changelist",
                "icon": "fas fa-robot",
                "permissions": ["catalog.view_aimodel"],
            },
        ],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth_system.User": "fas fa-user",
        "auth_system.SignupSettings": "fas fa-gift",
        "catalog": "fas fa-layer-group",
        "catalog.AIProvider": "fas fa-plug",
        "catalog.AIModel": "fas fa-robot",
        "catalog.CapabilityCategory": "fas fa-th-large",
        "catalog.CategoryPromptPreset": "fas fa-comment-dots",
        "catalog.ModelPromptPreset": "fas fa-comment-alt",
        "catalog.UserPromptPreset": "fas fa-bookmark",
        "rendering.RenderTask": "fas fa-spinner",
        "rendering.GeneratedImage": "fas fa-image",
        "billing.Plan": "fas fa-crown",
        "billing.CreditPack": "fas fa-coins",
        "billing.PricingSettings": "fas fa-tags",
        "billing.UserSubscription": "fas fa-receipt",
        "projects.Project": "fas fa-folder-open",
        "workflow.Workflow": "fas fa-project-diagram",
        "assets.Asset": "fas fa-file-image",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "catalog.aimodel": "collapsible",
        "catalog.aiprovider": "horizontal_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-teal",
    "navbar": "navbar-dark navbar-gray-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
