"""AI models for Image Generate (text / reference → image) via Fal.ai."""

IMAGE_GENERATE_MODELS = [
    {
        "slug": "nano-banana-2",
        "name": "Nano Banana",
        "description": "Nanobanana 2 — fast creative image generation",
        "tag": "new",
        "brand_icon": "nano-banana",
        "provider": "fal",
        "external_id": "nano-banana-2",
        "credit_cost": 3,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 4,
        "input_images_label": "Reference images",
        "input_images_help": "Optional style or composition references.",
        "default_positive": "high quality creative render, vivid detail",
        "config": {
            "endpoint_path": "fal-ai/nano-banana",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Enhance realism",
                "icon": "sparkles",
                "positive": "ultra photorealistic, 8k detail, cinematic lighting",
                "is_default": True,
            },
        ],
        "sort_order": 0,
    },
    {
        "slug": "nano-banana-pro",
        "name": "Nano Banana Pro",
        "description": "Nanobanana PRO — highest quality stills",
        "tag": "pro",
        "brand_icon": "nano-banana",
        "provider": "fal",
        "external_id": "nano-banana-pro",
        "credit_cost": 6,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 8,
        "input_images_label": "Reference images",
        "input_images_help": "Optional references for style and layout.",
        "default_positive": "professional viz, ultra sharp, studio lighting",
        "config": {
            "endpoint_path": "fal-ai/nano-banana-pro",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Studio render",
                "icon": "sparkles",
                "positive": "architectural visualization, clean studio light, 8k",
                "is_default": True,
            },
        ],
        "sort_order": 1,
    },
    {
        "slug": "flux-pro",
        "name": "Flux Pro",
        "description": "Flux — premium photorealistic generation",
        "tag": "pro",
        "brand_icon": "flux",
        "provider": "fal",
        "external_id": "black-forest-labs/flux-pro",
        "credit_cost": 4,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 12,
        "input_images_label": "Reference images",
        "input_images_help": "Optional sketches or photos to guide the render.",
        "default_positive": "photorealistic architectural visualization, natural lighting",
        "config": {
            "endpoint_path": "fal-ai/flux-pro",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Enhance realism",
                "icon": "sparkles",
                "positive": "ultra photorealistic, 8k detail, cinematic lighting, sharp focus",
                "negative": "cartoon, illustration, blurry",
                "is_default": True,
            },
        ],
        "sort_order": 2,
    },
    {
        "slug": "gpt-image",
        "name": "GPT Image",
        "description": "OpenAI image model — strong prompt adherence",
        "tag": "pro",
        "brand_icon": "gpt",
        "provider": "fal",
        "external_id": "gpt-image-1",
        "credit_cost": 5,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 4,
        "input_images_label": "Reference images",
        "input_images_help": "Optional reference for style transfer.",
        "default_positive": "detailed architectural visualization, realistic materials",
        "config": {
            "endpoint_path": "fal-ai/gpt-image-1.5",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Concept viz",
                "icon": "sparkles",
                "positive": "early concept render, soft lighting, design intent clear",
                "is_default": True,
            },
        ],
        "sort_order": 3,
    },
    {
        "slug": "seedream",
        "name": "Seedream",
        "description": "Seedream — creative stylized stills",
        "tag": "new",
        "brand_icon": "seedream",
        "provider": "fal",
        "external_id": "seedream-v1",
        "credit_cost": 3,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 6,
        "input_images_label": "Reference images",
        "input_images_help": "Optional mood and style references.",
        "default_positive": "stylized architectural art, rich color grading",
        "config": {
            "endpoint_path": "fal-ai/bytedance/seedream/v4/text-to-image",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Dreamy mood",
                "icon": "sparkles",
                "positive": "ethereal atmosphere, soft glow, cinematic color",
                "is_default": True,
            },
        ],
        "sort_order": 4,
    },
    {
        "slug": "magnific",
        "name": "Magnific",
        "description": "Magnific — upscale and hallucinate detail",
        "tag": "pro",
        "brand_icon": "magnific",
        "provider": "fal",
        "external_id": "magnific-v2",
        "credit_cost": 4,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to enhance with Magnific.",
        "default_positive": "enhance micro detail, sharp edges, photoreal texture",
        "config": {
            "endpoint_path": "fal-ai/clarity-upscaler",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "AI enhance",
                "icon": "sparkles",
                "positive": "enhance micro detail, sharpen edges, remove noise",
                "is_default": True,
            },
        ],
        "sort_order": 5,
    },
    {
        "slug": "flux-schnell",
        "name": "Flux Schnell",
        "description": "Fast photorealistic generation",
        "tag": "free",
        "brand_icon": "flux",
        "provider": "comfy",
        "external_id": "flux-schnell",
        "credit_cost": 2,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 12,
        "input_images_label": "Reference images",
        "input_images_help": "Optional — add sketches or photos to guide the render.",
        "default_positive": "photorealistic architectural visualization, natural lighting",
        "default_negative": "blurry, low quality, watermark",
        "config": {
            "endpoint_path": "flux-schnell",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Enhance realism",
                "icon": "sparkles",
                "positive": "ultra photorealistic, 8k detail, cinematic lighting, sharp focus",
                "negative": "cartoon, illustration, blurry",
                "is_default": True,
            },
        ],
        "sort_order": 6,
    },
    {
        "slug": "sdxl-arch",
        "name": "SDXL Architecture",
        "description": "Optimized for buildings and interiors",
        "tag": "free",
        "brand_icon": "",
        "provider": "comfy",
        "external_id": "sdxl-arch-v1",
        "credit_cost": 1,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 8,
        "input_images_label": "Reference images",
        "input_images_help": "Optional style and composition references.",
        "default_positive": "modern architecture render, clean lines, professional viz",
        "config": {
            "endpoint_path": "sdxl-arch-v1",
            "output_type": "image",
        },
        "presets": [
            {
                "title": "Axonometry",
                "icon": "ruler",
                "positive": "axonometric view, technical illustration style, white background",
                "negative": "perspective distortion",
                "is_default": True,
            },
        ],
        "sort_order": 7,
    },
]

IMAGE_GENERATE_ACTIVE_SLUGS = [m["slug"] for m in IMAGE_GENERATE_MODELS]
