"""AI models for the Image Edit capability."""

IMAGE_EDIT_MODELS = [
    {
        "slug": "nano-banana-2",
        "name": "Nano Banana 2",
        "description": "Precise edits with fast turnaround",
        "tag": "new",
        "brand_icon": "nano-banana",
        "provider": "fal",
        "external_id": "nano-banana-2-edit",
        "credit_cost": 3,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 4,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Precise", "Quality", "Fast"],
            "endpoint_path": "fal-ai/nano-banana/edit",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 0,
    },
    {
        "slug": "nano-banana-pro",
        "name": "Nano Banana Pro",
        "description": "Highest quality image edits",
        "tag": "pro",
        "brand_icon": "nano-banana",
        "provider": "fal",
        "external_id": "nano-banana-pro-edit",
        "credit_cost": 6,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 8,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Precise", "Quality"],
            "endpoint_path": "fal-ai/nano-banana-pro/edit",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 1,
    },
    {
        "slug": "flux-pro",
        "name": "Flux 2 Pro",
        "description": "Premium photorealistic edits",
        "tag": "pro",
        "brand_icon": "flux",
        "provider": "replicate",
        "external_id": "flux-pro-edit",
        "credit_cost": 4,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 4,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Quality"],
            "endpoint_path": "black-forest-labs/flux-pro",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 2,
    },
    {
        "slug": "gpt-image",
        "name": "GPT Image 1.5",
        "description": "Strong prompt adherence for edits",
        "tag": "pro",
        "brand_icon": "gpt",
        "provider": "openai",
        "external_id": "gpt-image-1.5-edit",
        "credit_cost": 5,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 4,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Style", "Precise"],
            "endpoint_path": "images/edits",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 3,
    },
    {
        "slug": "gpt-image-2",
        "name": "GPT Image 2",
        "description": "Latest OpenAI image editing",
        "tag": "new",
        "brand_icon": "gpt",
        "provider": "openai",
        "external_id": "gpt-image-2-edit",
        "credit_cost": 6,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 4,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Style"],
            "endpoint_path": "fal-ai/gpt-image-1.5/edit",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 4,
    },
    {
        "slug": "nano-banana",
        "name": "Nano Banana",
        "description": "Fast creative image edits",
        "tag": "free",
        "brand_icon": "nano-banana",
        "provider": "fal",
        "external_id": "nano-banana-edit",
        "credit_cost": 2,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 4,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Fast", "Quality"],
            "endpoint_path": "fal-ai/nano-banana/edit",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 5,
    },
    {
        "slug": "seedream",
        "name": "Seedream v4.5",
        "description": "Stylized edits on a budget",
        "tag": "pro",
        "brand_icon": "seedream",
        "provider": "fal",
        "external_id": "seedream-v4.5-edit",
        "credit_cost": 3,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 6,
        "input_images_label": "Source image",
        "input_images_help": "Upload the image to edit on the canvas.",
        "default_positive": "Create photorealistic image",
        "config": {
            "badges": ["Cheap", "Quality"],
            "endpoint_path": "fal-ai/bytedance/seedream/v4/edit",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 6,
    },
]

IMAGE_EDIT_ACTIVE_SLUGS = [m["slug"] for m in IMAGE_EDIT_MODELS]
