"""AI models for 3D Model Create (Fal.ai queue API where available)."""

MODEL_3D_MODELS = [
    {
        "slug": "meshy-3d",
        "name": "Meshy AI",
        "description": "Image or text to textured 3D model (Meshy v6)",
        "tag": "pro",
        "brand_icon": "meshy",
        "provider": "fal",
        "external_id": "meshy-v6",
        "credit_cost": 8,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 4,
        "input_images_label": "Reference images",
        "input_images_help": "Connect a Source image — photo guides the mesh shape and texture.",
        "default_positive": "clean topology, PBR textures, architectural prop",
        "config": {
            "output_type": "model3d",
            "endpoint_path": "fal-ai/meshy/v6/image-to-3d",
            "text_endpoint_path": "fal-ai/meshy/v6/text-to-3d",
            "multi_image_endpoint_path": "fal-ai/meshy/v5/multi-image-to-3d",
            "poll_interval_sec": 5,
            "timeout_sec": 900,
        },
        "presets": [
            {
                "title": "Architectural prop",
                "icon": "sparkles",
                "positive": "furniture or decor object, watertight mesh, realistic materials",
                "is_default": True,
            },
            {
                "title": "From photo",
                "icon": "image",
                "positive": "match reference silhouette, quad-friendly topology",
                "negative": "broken mesh, floating geometry",
            },
        ],
    },
    {
        "slug": "meshy-lite-3d",
        "name": "Meshy Lite",
        "description": "Fast text-to-3D preview mesh",
        "tag": "free",
        "brand_icon": "meshy",
        "provider": "fal",
        "external_id": "meshy-lite",
        "credit_cost": 2,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 1,
        "input_images_label": "Reference image",
        "input_images_help": "Optional — connect a Source for image-guided mesh.",
        "default_positive": "simple 3D object, low poly preview",
        "config": {
            "output_type": "model3d",
            "endpoint_path": "fal-ai/meshy/v6/text-to-3d",
            "image_endpoint_path": "fal-ai/meshy/v6/image-to-3d",
            "poll_interval_sec": 4,
            "timeout_sec": 600,
        },
        "presets": [
            {
                "title": "Quick blockout",
                "icon": "sparkles",
                "positive": "low poly blockout, readable silhouette",
                "is_default": True,
            },
        ],
    },
    {
        "slug": "tripo3d",
        "name": "Tripo3D",
        "description": "Tripo v2.5 — high quality image or text to 3D",
        "tag": "new",
        "brand_icon": "tripo",
        "provider": "fal",
        "external_id": "tripo-v2.5",
        "credit_cost": 6,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 4,
        "input_images_label": "Reference images",
        "input_images_help": "Front photo or concept art on canvas Source node.",
        "default_positive": "detailed 3D asset, clean UVs, game-ready",
        "config": {
            "output_type": "model3d",
            "endpoint_path": "tripo3d/tripo/v2.5/image-to-3d",
            "text_endpoint_path": "tripo3d/tripo/v2.5/text-to-3d",
            "poll_interval_sec": 5,
            "timeout_sec": 900,
        },
        "presets": [
            {
                "title": "Product viz",
                "icon": "sparkles",
                "positive": "product hero object, studio lighting baked to texture",
                "is_default": True,
            },
        ],
    },
    {
        "slug": "rodin",
        "name": "Rodin",
        "description": "Hyperhuman Rodin — detailed organic & hard-surface 3D",
        "tag": "pro",
        "brand_icon": "rodin",
        "provider": "hyperhuman",
        "external_id": "rodin-v1",
        "credit_cost": 10,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 2,
        "input_images_label": "Reference images",
        "input_images_help": "Optional concept or orthographic references.",
        "default_positive": "high detail sculpt, realistic proportions",
        "config": {"output_type": "model3d"},
        "presets": [
            {
                "title": "Character bust",
                "icon": "sparkles",
                "positive": "character bust, fine surface detail, production mesh",
                "is_default": True,
            },
        ],
    },
    {
        "slug": "hunyuan3d",
        "name": "Hunyuan3D",
        "description": "Tencent Hunyuan3D — fast text/image to mesh",
        "tag": "new",
        "brand_icon": "hunyuan",
        "provider": "tencent",
        "external_id": "hunyuan3d-v1",
        "credit_cost": 5,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 3,
        "input_images_label": "Reference images",
        "input_images_help": "Optional multi-view or single photo.",
        "default_positive": "coherent 3D shape, consistent materials",
        "config": {"output_type": "model3d"},
        "presets": [
            {
                "title": "Scene object",
                "icon": "sparkles",
                "positive": "environment prop, stylized realism, export-ready",
                "is_default": True,
            },
        ],
    },
    {
        "slug": "luma-genie",
        "name": "Luma Genie",
        "description": "Luma — cinematic 3D from text or image",
        "tag": "pro",
        "brand_icon": "luma",
        "provider": "luma",
        "external_id": "genie-v1",
        "credit_cost": 7,
        "requires_images": False,
        "min_input_images": 0,
        "max_input_images": 2,
        "input_images_label": "Reference image",
        "input_images_help": "Optional image for image-to-3D.",
        "default_positive": "cinematic 3D asset, smooth shading",
        "config": {"output_type": "model3d"},
        "presets": [
            {
                "title": "NeRF-style object",
                "icon": "sparkles",
                "positive": "single object, view-consistent, mesh export",
                "is_default": True,
            },
        ],
    },
    {
        "slug": "csm-ai",
        "name": "CSM AI",
        "description": "Common Sense Machines — image to 3D scene mesh",
        "tag": "pro",
        "brand_icon": "csm",
        "provider": "fal",
        "external_id": "triposr",
        "credit_cost": 9,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source image",
        "input_images_help": "One photo drives the 3D reconstruction.",
        "default_positive": "scene reconstruction, depth-aware geometry",
        "config": {
            "output_type": "model3d",
            "endpoint_path": "fal-ai/triposr",
            "poll_interval_sec": 3,
            "timeout_sec": 300,
        },
        "presets": [
            {
                "title": "Interior scan",
                "icon": "sparkles",
                "positive": "room-scale mesh, furniture separated, clean normals",
                "is_default": True,
            },
        ],
    },
]

MODEL_3D_ACTIVE_SLUGS = [m["slug"] for m in MODEL_3D_MODELS]
