"""AI models for the Image Upscaler capability."""

UPSCALE_MODELS = [
    {
        "slug": "pro-upscaler",
        "name": "Pro Upscaler",
        "description": "Fast, high-quality upscaling for production renders",
        "tag": "pro",
        "brand_icon": "upscale",
        "provider": "comfy",
        "external_id": "pro-upscaler",
        "credit_cost": 2,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Image to upscale",
        "input_images_help": "Upload the image to enhance.",
        "default_positive": "enhance micro detail, sharpen edges, upscale 4x, photorealistic",
        "config": {
            "badges": ["Cheap", "Quality"],
            "endpoint_path": "pro-upscaler",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 0,
    },
    {
        "slug": "magnific-creative",
        "name": "Magnific Creative",
        "description": "Hallucinate creative detail while upscaling",
        "tag": "pro",
        "brand_icon": "magnific",
        "provider": "magnific",
        "external_id": "magnific-creative",
        "credit_cost": 5,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Image to upscale",
        "input_images_help": "Upload the image to enhance.",
        "default_positive": "creative detail enhancement, upscale, vivid textures, artistic refinement",
        "config": {
            "badges": ["Add details"],
            "endpoint_path": "v1/upscale/creative",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 1,
    },
    {
        "slug": "magnific-precision-v2",
        "name": "Magnific Precision v2",
        "description": "Precise detail recovery without changing composition",
        "tag": "pro",
        "brand_icon": "magnific",
        "provider": "magnific",
        "external_id": "magnific-precision-v2",
        "credit_cost": 6,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Image to upscale",
        "input_images_help": "Upload the image to enhance.",
        "default_positive": "precise upscale, faithful detail recovery, sharp edges, no composition change",
        "config": {
            "badges": ["Add details", "Quality"],
            "endpoint_path": "v1/upscale/precision-v2",
            "output_type": "image",
        },
        "presets": [],
        "sort_order": 2,
    },
]

UPSCALE_ACTIVE_SLUGS = [m["slug"] for m in UPSCALE_MODELS]
