"""AI models for the Video Creator capability."""

VIDEO_MODELS = [
    {
        "slug": "veo-3-1",
        "name": "Veo 3.1",
        "description": "Google Veo — cinematic video with optional audio",
        "tag": "pro",
        "brand_icon": "veo",
        "provider": "fal",
        "external_id": "veo-3.1",
        "credit_cost": 14,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source frame",
        "input_images_help": "Upload the still image to animate.",
        "default_positive": "cinematic camera motion, stable scene, 24fps",
        "config": {
            "badges": ["1080p", "Last frame", "Audio"],
            "endpoint_path": "fal-ai/veo3/image-to-video",
            "output_type": "video",
        },
        "presets": [],
        "sort_order": 0,
    },
    {
        "slug": "kling-pro",
        "name": "Kling",
        "description": "High quality image-to-video motion",
        "tag": "pro",
        "brand_icon": "kling",
        "provider": "fal",
        "external_id": "kling-v1.6",
        "credit_cost": 10,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source frame",
        "input_images_help": "Upload the still image to animate.",
        "default_positive": "cinematic camera motion, stable architecture, 24fps",
        "config": {
            "badges": ["1080p", "Quality"],
            "endpoint_path": "fal-ai/kling-video/v1.6/standard/image-to-video",
            "output_type": "video",
        },
        "presets": [],
        "sort_order": 1,
    },
    {
        "slug": "seedance",
        "name": "Seedance",
        "description": "Rhythmic motion from stills",
        "tag": "new",
        "brand_icon": "seedance",
        "provider": "fal",
        "external_id": "seedance-v1",
        "credit_cost": 8,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source frame",
        "input_images_help": "One image drives the clip.",
        "default_positive": "fluid motion, dynamic camera, stable scene",
        "config": {
            "badges": ["Fast", "Quality"],
            "endpoint_path": "fal-ai/bytedance/seedance/v1/image-to-video",
            "output_type": "video",
        },
        "presets": [],
        "sort_order": 2,
    },
    {
        "slug": "runway-gen3",
        "name": "Runway Gen-3",
        "description": "High quality motion with style control",
        "tag": "pro",
        "brand_icon": "runway",
        "provider": "fal",
        "external_id": "gen3-turbo",
        "credit_cost": 12,
        "requires_images": True,
        "min_input_images": 1,
        "max_input_images": 1,
        "input_images_label": "Source frame",
        "input_images_help": "One image drives the video.",
        "default_positive": "cinematic motion, realistic lighting",
        "config": {
            "badges": ["1080p"],
            "endpoint_path": "fal-ai/runway-gen3/turbo/image-to-video",
            "output_type": "video",
        },
        "presets": [],
        "sort_order": 3,
    },
]

VIDEO_ACTIVE_SLUGS = [m["slug"] for m in VIDEO_MODELS]
