# Generated by Django 5.2.14 on 2026-05-17 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapabilityCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="sparkles",
                        help_text="Lucide icon name for the frontend (e.g. image, video, wand-sparkles)",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "capability categories",
                "db_table": "capability_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=64)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider model id / Comfy workflow id",
                        max_length=256,
                    ),
                ),
                ("credit_cost", models.PositiveIntegerField(default=1)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("default_positive", models.TextField(blank=True)),
                ("default_negative", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.capabilitycategory",
                    ),
                ),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["sort_order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ModelPromptPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=128)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("positive_prompt", models.TextField()),
                ("negative_prompt", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_presets",
                        to="catalog.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "model_prompt_presets",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
