# Generated by Django 5.2.14 on 2026-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="input_images_help",
            field=models.TextField(
                blank=True, help_text="Hint text under the upload area"
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="input_images_label",
            field=models.CharField(
                blank=True,
                default="Input images",
                help_text="Label shown in the editor sidebar",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="max_input_images",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Maximum images allowed; 0 = unlimited"
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="min_input_images",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minimum images required (0 = optional)"
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="requires_images",
            field=models.BooleanField(
                default=False,
                help_text="Whether this model expects image input(s) before running",
            ),
        ),
    ]
